version: '3.3'

services:
  app1:
    image: traefik/whoami
    ports:
      - '5001:80'
    environment:
      WHOAMI_NAME: app1
  app2:
    image: traefik/whoami
    ports:
      - '5002:80'
    environment:
      WHOAMI_NAME: app2
  app3:
    image: traefik/whoami
    ports:
      - '5003:80'
    environment:
      WHOAMI_NAME: app3
  lb:
    build: .
    depends_on:
      - app1
      - app2
      - app3
    ports:
      - '80:80'

volumes:
      lb_data:
